### ISSUE TITLE
Would like to reformat `README.md`

### ISSUE THREAD

**Issue by dishantvyas15** [Archish27/nora-covid-19-bot#17]
**Issue**
Hi 👋 @Archish27 
I liked the concept of this repository and was going through your project when I came across some areas in `README.md` which can be made more reader-friendly.

**Solution**
I'm keen to make these two changes:
- Decrease the size of the project logo to make it look better.
- Apply some spacing at the end of each section so that all such are well-separated and easy to read.

This might not be an extremely valuable contribution, but still, as the readme file decides whether the readers will be interested in the project or not, I'd love to make the reading experience a bit better!

**Additional request**
Requesting assignment under `hacktoberfest` label :)

**Comment by Archish27** [comment]
@dishantvyas15 Nice suggestion please go ahead 👍  Will add label to it.

**Comment by Archish27** [comment]
Also, check if you can make contributing guide better there are some verbal & markdown mistakes too.

**Comment by dishantvyas15** [comment]
> Also, check if you can make contributing guide better there are some verbal & markdown mistakes too.

Sure @Archish27, will look into that too.
